### ISSUE TITLE
Doesnt work with Xaero's minimap (fair-play)

### ISSUE THREAD

**Issue by IZeeXeS** [fewwan/xaeros-map-chest-tracker-integration#1]
### Bug description

mod can only work with default Xaero map

### Steps to reproduce

1. Install Xaero's minimap (fair-play)
2. Add this mod

### Expected behavior

this mod should work with Xaero's minimap (fair-play)

### Actual behavior

doesnt work

### Minecraft version

1.20.1

### TemplateMod version

23.4.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by fewwan** [comment]
Thanks for reporting this issue.
Unfortunately, a different file is needed for the fear play version.
The new version can be downloaded [here](https://github.com/fewwan/xaeros-map-chest-tracker-integration/releases). Use the version that starts with FP.
