### ISSUE TITLE
compatibility with better pvp

### ISSUE THREAD

**Issue by krispyking24** [fewwan/xaeros-map-chest-tracker-integration#5]
### Bug description

long story short make it work with better pvp too as xaero's minimap cant be loaded with it
the game doesnt load due to the mod requiring xaero's minimap which conflicts with their better pvp mod due to I think the same mixins

### Steps to reproduce

have Xaero's Map Chest Tracker Integration and better pvp mod in the same folder. it wont load so I added xaero's minimap and that caused an issue with better pvp

### Expected behavior

for the game to load

### Actual behavior

the game doesnt load due to the mod requiring xaero's minimap which conflicts with their better pvp mod due to I think the same mixins

### Minecraft version

1.19.4

### Xaero's Map Chest Tracker Integration version

1.0.1

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by fewwan** [comment]
It's fixed in the new release 1.0.2.
