### ISSUE TITLE
You forgot about BetterPVP mod

### ISSUE THREAD

**Issue by AdolfRoxler** [fewwan/xaeros-map-chest-tracker-integration#6]
### Bug description

BetterPVP also includes the minimap

### Steps to reproduce

Install betterPVP instead of minimap

### Expected behavior

well honestly it should work

### Actual behavior

it halts fabric and screams about it wanting the heckin minimap

### Relevant logs

irrelevant lol

### Minecraft version

1.20.1

### Xaero's Map Chest Tracker Integration version

1.0.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by fewwan** [comment]
It's fixed in the new release 1.0.2.
