### ISSUE TITLE
Crash when using Chest Tracker 2.4.2 (mc 1.20.4)

### ISSUE THREAD

**Issue by Hlebuw3k** [fewwan/xaeros-map-chest-tracker-integration#7]
### Bug description

When clicking on an item in the chest tracker menu to search for it, and having xaeros map integration mod installed and enabled, the game will instantly crash. For example, clicking on any of these items will crash the game:
![image](https://github.com/fewwan/xaeros-map-chest-tracker-integration/assets/78320892/3a808705-fccf-4c62-933f-366a007725a6)
The game does not crash if xaeros map integration is not installed with the chest tracker mod.

### Steps to reproduce

1. Put an item in a chest
2. Search for that item

### Relevant logs

[crash-2024-05-12_19.41.55-client.txt](https://github.com/fewwan/xaeros-map-chest-tracker-integration/files/15287070/crash-2024-05-12_19.41.55-client.txt)

### Minecraft version

1.20.4

### Xaero's Map Chest Tracker Integration version

2.0.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Iron-Squid** [comment]
I can confirm that the same issue afflicts me.

**Comment by Ice129** [comment]
same issue found here

**Comment by Hlebuw3k** [comment]
Does not crash if Chest Tracker is downgraded to or before version 2.3.3
Chest Tracker 2.4.2 update notes include "Note: There has been a fairly large internal reshuffling of packages; most mods using the API or internal classes will need an update, so please be patient." https://modrinth.com/mod/chest-tracker/version/2.4.2+1.20.4

**Comment by fewwan** [comment]
I'm sorry I haven't been able to update or fix any bugs, I've had personal matters, and other projects to prioritize, I will get to work right away
