### ISSUE TITLE
update to 1.21 please

### ISSUE THREAD

**Issue by rufwyll** [fewwan/xaeros-map-chest-tracker-integration#9]
### Motivation

I would be very grateful if you update the mod version to 1.21

### Description

-

### Other information

-

**Comment by fewwan** [comment]
I'm sorry I haven't been able to update or fix any bugs, I've had personal matters, and other projects to prioritize, I will get to work right away

**Comment by rufwyll** [comment]
> Извините, я не смог обновить или исправить какие-либо ошибки, у меня были личные дела и другие проекты, которые нужно было отдать приоритет, я сразу приступлю к работе

no problem) thank you for doing this and making the game process easier🫶🏻

**Comment by fewwan** [comment]
The new version is now available. Enjoy!
If you have any suggestions or feedback, feel free to share them.
